# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322d52d64c34a3461800a7a22dbe852eabe8da6552d84dd39170d48ab4e477340743936871923e0386b8745ef6c5d1d03212e312e9ed8500b726701b73837bb3

test:
  secret_key_base: 4248ce6d06d649758dd0ddd2f8d45836230ab94b9d43493cb350d74775a12df803c922421e291495c5b9406f05bbdfa3243a61f4448b53b02e40d5b8f1f34b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
